# Generated by Django 2.0.6 on 2019-03-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='bj_user',
        ),
    ]
